[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/games"
  to = "/games.html"
  status = 200

[[redirects]]
  from = "/apps"
  to = "/apps.html"
  status = 200

[[redirects]]
  from = "/browser"
  to = "/browser.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings.html"
  status = 200

[[redirects]]
  from = "/credits"
  to = "/credits.html"
  status = 200

[[redirects]]
  from = "/social-media-partners"
  to = "/social-media-&-partners.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/account.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/music"
  to = "/music.html"
  status = 200

[[redirects]]
  from = "/rift_media"
  to = "/rift_media.html"
  status = 200

[[redirects]]
  from = "/os"
  to = "/os.html"
  status = 200

[[redirects]]
  from = "/os/*"
  to = "/os/:splat.html"
  status = 200
